### PR TITLE
Handle error when no pages were found while crawling

### LINKED ISSUE #24: Some HTTPS URLs fail
HTTPS URL:
```
> node dist/scan_task.js "https://www.dfwfreeways.com/"
Created CSV file
Starting the crawl...
Scan complete
Aggregating reports...
TypeError [ERR_STREAM_NULL_VALUES]: May not write null values to stream
```

HTTP URL:
```
> node dist/scan_task.js "http://www.dfwfreeways.com/"
Created CSV file
Starting the crawl...
Crawled http://www.dfwfreeways.com/ [text/html; charset=utf-8] (79176 bytes)
Report is done for http://www.dfwfreeways.com/
Wrote report for http://www.dfwfreeways.com/
```

@emersonthis said that it is probably an issue with the `www`, not with `https`

### PR DESCRIPTION
**Pull request by calebeby**
Closes #24

### CODE REVIEW

File: scan-task.ts [hunk 1]
```diff
@@ -55,6 +58,11 @@ crawler.on('fetchcomplete', (queueItem, responseBuffer, response) => {
 });
 crawler.on('complete', function () {
   console.log('Scan complete');
+  if (!hasFoundAnyPages) {
+    console.error('No pages were found while crawling site; exiting');
```
Comment (emersonthis) [inline scan-task.ts:62]: Do you think we can make this a bit more helpful? I _think_ it's true that the only time this can happen is when the user puts in a bad URL. Even a site with only one page would return one result. So I think it might be safe to suggest here that the user might have made a mistake with the URL. What do you think? There's nothing untrue about the current message, but it seems a little bit vague/opaque for what might be a pretty specific situation. 

Suggestion: `No pages were found for this site. The two most likely reasons for this are: 1) the URL is incorrect or 2) the crawler is being denied by a robots.txt file.` 

Thoughts?

Comment (calebeby) [reply scan-task.ts]: Updated!

**Comment by emersonthis** [comment]
Shoot, I forgot to mention previously... This feels like something we should write a test for. Thoughts?

**Comment by calebeby** [comment]
@emersonthis I think it does make sense to have a test, but I'm not sure how easy it is to test this currently because the `scan-task.ts` file has args passed in as CLI arguments. Do you know of any ways I can test this?

Maybe I can write a TODO test for this PR, and once #25 is done, we should be able to test it like this:
```js
import { scan } from './scan-task'
test('Displays useful error if no pages are found while crawling', () => {
  const result = await scan('https://nonexistent-website.com')
  expect(result.error).toMatch(/No pages were found for this site/)
})
```

**Comment by emersonthis** [comment]
@calebeby there probably is a way to do what you asked, but i think your plan is fine. Please also create an issue and put the URL in the TODO comment. Something to mention in that issue: currently test you showed will try to make a live request. We can get away with it for this test, but it's hacky for tests to make live requests. Also very slow. Sooner than later we need to figure out a way to do this the right way. So maybe we take our time with that future issue when we get there.

**Review by emersonthis — APPROVED** [review]
